### ISSUE TITLE
Question Regarding Data Structure for Echo Chamber Analysis

### ISSUE THREAD

**Issue by adafnos** [faalatawi/echo-chamber-score#1]
Hi, 

thanks for making the code public, this is a very interesting way to study echo chambers. I am planning to use your approach for my case as well. But I have a question about the structure of your datasets. I noticed that the values of the _user_id_ and _retweets_ columns are unique. In my case, the same _user_id_ or even _tweets_ appear more than one time. Is this problematic in your opinion?

Thanks, 
Andreas

**Comment by faalatawi** [comment]
Thank you for your interest. 

Could you give more details about the issue? Which dataset, file, and user_id?

**Comment by adafnos** [comment]
For example, if you analyse the gun dataset (data/gun/tweets.feather), it has two columns, i.e. user_id and tweets. The shape of the dataframe is (6941, 2). The length of the unique values in the user_id column is also 6941. This is not the case with my data. 

I'm asking this question because after trying your code, I always get two communities: one very small one with, say, < 50 nodes and another with > 30000 nodes. I tried different time intervals for the RT networks, but the results are always the same: one small community and another large one. I just wanted to make sure that the structure of my dataset doesn't affect the results.

**Comment by faalatawi** [comment]
Which code? Are you talking about community detection?

**Comment by adafnos** [comment]
Hi, everything works fine now. I hadn't realised that I needed to group together all the tweets that belong to the same user, that's why the results did not make sense.
